### PR TITLE
Upgrade mypy to latest version. Turn off strict mode.

### LINKED ISSUE #825: Mypy failure: 'error: <nothing> has no attribute "pipe"'
This is happening on the main build: e.g. https://github.com/pystatgen/sgkit/runs/5312420654?check_suite_focus=true

```
Check for merge conflicts................................................Passed
Debug Statements (Python)................................................Passed
Mixed line ending........................................................Passed
Check for case conflicts.................................................Passed
Check Yaml...............................................................Passed
isort....................................................................Passed
black....................................................................Passed
flake8...................................................................Passed
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

sgkit/tests/test_pc_relate.py:105: error: <nothing> has no attribute "pipe"  [attr-defined]
sgkit/tests/test_pc_relate.py:143: error: <nothing> has no attribute "pipe"  [attr-defined]
```

### PR DESCRIPTION
**Pull request by tomwhite**
Fixes #825.

I have turned off mypy's strict mode since it was having so many problems with imports. I've fixed the remaining errors, but I do wonder whether we are getting much value from mypy. Are we doing it wrong, or do other projects have to work as hard to keep the build working?

### CODE REVIEW

**Comment by tomwhite** [comment]
This is failing due to the unrelated error in #828.

**Comment by jeromekelleher** [comment]
> but I do wonder whether we are getting much value from mypy. 

It seems like much more trouble than it's worth IMO

**Comment by tomwhite** [comment]
This is passing now that I've pinned Zarr (see #828).

**Comment by tomwhite** [comment]
I will merge if this looks ok to you @jeromekelleher?

**Review by jeromekelleher — APPROVED** [review]
