### ISSUE TITLE
Conda: ImportError: cannot import name 'Ttest_1sampResult' from 'scipy.stats.stats'

### ISSUE THREAD

**Issue by alxsimon** [pystatgen/sgkit#1016]
Hi, I keep hitting what seems to be a version compatibility issue but I've had a hard time trying to solve this.

`ImportError: cannot import name 'Ttest_1sampResult' from 'scipy.stats.stats'`

Here is the simple conda env giving me this error:
```
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - sgkit=0.5.0
```

Feels like there is a dependency rule missing somewhere in the conda recipe.
I've tried a lot of combinations of sgkit, scipy, python, numpy but didn't manage to solve this.

Thanks

**Comment by alxsimon** [comment]
Doing some more tests it seems to work with `scipy<1.10`, so this should probably be added to the conda recipe for sgkit.

**Comment by jeromekelleher** [comment]
I think we've hit this somewhere else @benjeffery?

A pr for the conda-forge feedstock with the appropriate pinning would be much appreciated @alxsimon!

**Comment by benjeffery** [comment]
I hit this locally, happy to do the conda PR.

**Comment by alxsimon** [comment]
Maybe it can be included in the pending v0.6 PR?

https://github.com/conda-forge/sgkit-feedstock/pull/5

**Comment by jeromekelleher** [comment]
I've updated the sgkit-feedstock PR, but left scipy pinning along because we don't have one on the pip package. Do remember what was causing this error for us @benjeffery?

**Comment by alxsimon** [comment]
related to #789 also

**Comment by alxsimon** [comment]
Probably linked to this in Dask https://github.com/dask/dask/commit/a27b437da2594fd5c15f85736aa520feb726ddbd

**Comment by jeromekelleher** [comment]
Great - will merge the feedstock after @tomwhite give's thumbs up

**Comment by benjeffery** [comment]
Yep, that was the issue we had too, so this PR should solve it.

**Comment by alxsimon** [comment]
new version working for me, thanks!
