### PR TITLE
Don't use Numba 0.54.0 since it doesn't work with NumPy 1.21

### LINKED ISSUE #654: Build failing with ImportError: cannot import name 'NDArray' from 'numpy.typing'
The problem is that the latest numba release (0.54.0) does not support NumPy 1.21, so it installs an earlier version, which doesn't have the `NDArray` type.

Stacktrace:

```
python exec: /opt/hostedtoolcache/Python/3.8.11/x64/bin/python
sys.path: ['/home/runner/work/sgkit/sgkit', '/opt/hostedtoolcache/Python/3.8.11/x64/bin', '/home/runner/work/sgkit/sgkit', '/opt/hostedtoolcache/Python/3.8.11/x64/lib/python38.zip', '/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8', '/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/lib-dynload', '/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages']
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/sphinx/config.py", line 327, in eval_config_file
    execfile_(filename, namespace)
  File "/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/home/runner/work/sgkit/sgkit/docs/conf.py", line 31, in <module>
    import sgkit  # noqa: F401 isort:skip
  File "/home/runner/work/sgkit/sgkit/sgkit/__init__.py", line 29, in <module>
    from .stats.hwe import hardy_weinberg_test
  File "/home/runner/work/sgkit/sgkit/sgkit/stats/hwe.py", line 6, in <module>
    from numpy.typing import NDArray
ImportError: cannot import name 'NDArray' from 'numpy.typing' (/opt/hostedtoolcache/Python/3.8.11/x64/lib/python3.8/site-packages/numpy/typing/__init__.py)
```

from https://github.com/pystatgen/sgkit/runs/3457090105?check_suite_focus=true

### PR DESCRIPTION
**Pull request by tomwhite**
Fixes #654.

This is a point fix, which may break again when Numba 0.54.1 is released - but we should probably re-evaluate at that point (since it is possible that Numba will support NumPy 1.21 at that point).

### CODE REVIEW

**Review by jeromekelleher — APPROVED** [review]
LGTM
